### ISSUE TITLE
Bag UI drag and drop

### ISSUE THREAD

**Issue by thamma** [neo-engine/neo#3]
- Issue: Dragging from anywhere on the bag screen to a pokemon picks up their item
- Reproducible: 100%
- Reproduction: 
  - open bag while carrying pokemons that hold items
  - drag (for instance from the right-hand side) 'nothing' to the pokemon
    - this also works if you start dragging on an item inside your bag while not waiting for its background to light up ([reproduction](https://gfycat.com/SelfishUnkemptBaiji) notice i start dragging whilst hovering the item on the right)
  - your cursor will now carry the pokemons item

**Comment by PH111P** [comment]
I changed the bag behavior to always display the sprite of the last touched item. That way one can prevent the pop-up of a sprite by moving the stylus to some “dead area”, i.e. the back/navigation buttons.
