### ISSUE TITLE
"Currently at [...]" popping up repeatedly

### ISSUE THREAD

**Issue by thamma** [neo-engine/neo#4]
- Issue: "The currently at [...]" dialoge pops up repeatedly even after closing
- Emulator: No$gba v2.6a
- Reproducible: 100%
- Reproduction: 
  - Alt-tabbing out of the emulator and re-entering the game pops up the dialogue
  - "okay"-ing on the touchscreen does clear the box but it reappears 
    - you can free yourself from the lock by hitting L (which is not defined in the [controls](http://i.imgur.com/nOgdrva.png))

**Comment by PH111P** [comment]
It's a debug feature which is bound to the L-Key.
I guess it can be fixed through the control configs of your emulator.
